### ISSUE TITLE
JS functions we need to write

### ISSUE THREAD

**Issue by melikecode** [charlottebrf/DoctorsWhoCode#13]
- How do we display a graph? What information needs to be passed to the <script> section of the .erb file so that it plays nice with javascript?

-Do I see a graph of cumulative time spent on each of all the activities I logged today?

- Are entries in the graph of cumulative time spent on each of all the activities I logged today ordered by descending duration?

Ainslie can work on writing some functions to get the info to display in text form

**Comment by sohbaker** [comment]
Re - culmulative time it seems we may need to install the 'groupdate' gem. 
It will allow us to group an activity by day/week,/etc and will automatically sort the activities in ascending order of time spent. We can set the time zone with a line of code so that it understands what day the activity was logged.

https://github.com/ankane/groupdate

I still have to work out how this will play with the rest of the data that the chart needs to filter from the logged activities, but hopefully we can get it working. Will look at this more in class tonight and ideally want to get it working by end of session today

**Comment by sohbaker** [comment]
Just realising the cumulative timing query looks similar to issue #16 in which case it may already be resolved...

**Comment by melikecode** [comment]
Oops I forgot to close this one. Already completed
